-- ValueLens / Portfolio of Portfolios core schema
create table if not exists public.pop_assets (
  symbol text primary key,
  name text not null,
  category text not null,
  target_weight numeric(5,2) not null check (target_weight >= 0 and target_weight <= 100),
  cg_id text,
  thesis text not null,
  token_capture_grade text not null,
  institutional_grade text not null,
  productive_route text,
  node_requirement text,
  conviction text not null,
  sort_order integer not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.pop_signals (
  id bigint generated by default as identity primary key,
  signal_date date not null,
  region text not null,
  institution text not null,
  headline text not null,
  fact text not null,
  source_label text not null,
  source_url text not null,
  impact_score smallint not null check (impact_score between 1 and 5),
  asset_symbols text[] not null default '{}',
  created_at timestamptz not null default now()
);

create table if not exists public.pop_productive_routes (
  id bigint generated by default as identity primary key,
  symbol text not null references public.pop_assets(symbol) on delete cascade,
  route_type text not null,
  route_name text not null,
  requirement text,
  reward_basis text,
  custody_model text not null,
  status text not null,
  source_url text,
  sort_order integer not null default 100,
  created_at timestamptz not null default now()
);

alter table public.pop_assets enable row level security;
alter table public.pop_signals enable row level security;
alter table public.pop_productive_routes enable row level security;

drop policy if exists "pop_assets_public_read" on public.pop_assets;
create policy "pop_assets_public_read" on public.pop_assets
for select to anon, authenticated using (active = true);

drop policy if exists "pop_signals_public_read" on public.pop_signals;
create policy "pop_signals_public_read" on public.pop_signals
for select to anon, authenticated using (true);

drop policy if exists "pop_routes_public_read" on public.pop_productive_routes;
create policy "pop_routes_public_read" on public.pop_productive_routes
for select to anon, authenticated using (true);

grant select on public.pop_assets to anon, authenticated;
grant select on public.pop_signals to anon, authenticated;
grant select on public.pop_productive_routes to anon, authenticated;
